<?php

return [
  'menu_order' => [
    ['route' => 'admin.anak.index', 'perm' => 'menu.siswa'],
    ['route' => 'admin.pendaftaran.index', 'perm' => 'menu.pendaftaran'],
    ['route' => 'admin.kelas.index', 'perm' => 'menu.kelola-kelas'],
    ['route' => 'admin.presensi.index', 'perm' => 'menu.presensi-siswa'],
    ['route' => 'admin.kesehatan.index', 'perm' => 'menu.kesehatan-siswa'],
    ['route' => 'admin.matrikulasi.index', 'perm' => 'menu.matrikulasi'],
    ['route' => 'admin.skala-pencapaian.index', 'perm' => 'menu.skala-capaian'],
    ['route' => 'admin.kegiatan.index', 'perm' => 'menu.agenda-belajar'],
    ['route' => 'admin.master-kegiatan-rutin.index', 'perm' => 'menu.kegiatan-rutin'],
    ['route' => 'admin.pencapaian.index', 'perm' => 'menu.pencapaian-siswa'],
    ['route' => 'admin.monev.index', 'perm' => 'menu.monev'],
    ['route' => 'admin.pengajar.index', 'perm' => 'menu.data-pengajar'],
    ['route' => 'admin.presensi-guru.index', 'perm' => 'menu.presensi-guru'],
    ['route' => 'admin.sarana.index', 'perm' => 'menu.sarana'],
    ['route' => 'admin.menu-makanan.index', 'perm' => 'menu.menu-makanan'],
    ['route' => 'admin.akun.index', 'perm' => 'menu.akun-coa'],
    ['route' => 'admin.cashflow.index', 'perm' => 'menu.cashflow'],
    ['route' => 'admin.jurnal.index', 'perm' => 'menu.jurnal-umum'],
    ['route' => 'admin.sumber-dana.index', 'perm' => 'menu.sumber-dana'],
    ['route' => 'admin.rkas.index', 'perm' => 'menu.rkas'],
    ['route' => 'admin.rkas.laporan', 'perm' => 'menu.laporan-rkas'],
    ['route' => 'admin.biaya-bulanan.index', 'perm' => 'menu.biaya-harian'],
    ['route' => 'admin.diskon.index', 'perm' => 'menu.diskon'],
    ['route' => 'admin.pembayaran-bulanan.index', 'perm' => 'menu.rekap-pembayaran'],
    ['route' => 'admin.kritik-saran.index', 'perm' => 'menu.kritik-saran'],
    ['route' => 'admin.orangtua-chat.index', 'perm' => 'menu.chat-orangtua'],
    ['route' => 'admin.role.index', 'perm' => 'menu.role'],
    ['route' => 'admin.pengguna.index', 'perm' => 'menu.pengguna'],
    ['route' => 'admin.akuntansi-setting.index', 'perm' => 'menu.setting-akuntansi'],
    ['route' => 'admin.ai-persona.index', 'perm' => 'menu.pengaturan-ai'],
  ],

  'route_permissions' => [
    'admin.anak.*' => 'menu.siswa',
    'admin.orang-tua.search' => 'menu.siswa',
    'admin.pendaftaran.*' => 'menu.pendaftaran',
    'admin.kelas.*' => 'menu.kelola-kelas',
    'admin.presensi.*' => 'menu.presensi-siswa',
    'admin.kesehatan.*' => 'menu.kesehatan-siswa',
    'admin.matrikulasi.*' => 'menu.matrikulasi',
    'admin.skala-pencapaian.*' => 'menu.skala-capaian',
    'admin.kegiatan.*' => 'menu.agenda-belajar',
    'admin.master-kegiatan-rutin.*' => 'menu.kegiatan-rutin',
    'admin.kegiatan-rutin.*' => 'menu.kegiatan-rutin',
    'admin.pencapaian.*' => 'menu.pencapaian-siswa',
    'admin.monev.*' => 'menu.monev',
    'admin.pengajar.*' => 'menu.data-pengajar',
    'admin.presensi-guru.*' => 'menu.presensi-guru',
    'admin.sarana.*' => 'menu.sarana',
    'admin.menu-makanan.*' => 'menu.menu-makanan',
    'admin.akun.*' => 'menu.akun-coa',
    'admin.cashflow.*' => 'menu.cashflow',
    'admin.jurnal.*' => 'menu.jurnal-umum',
    'admin.sumber-dana.*' => 'menu.sumber-dana',
    'admin.rkas.laporan' => 'menu.laporan-rkas',
    'admin.rkas.export-pdf' => 'menu.laporan-rkas',
    'admin.rkas.*' => 'menu.rkas',
    'admin.biaya-bulanan.*' => 'menu.biaya-harian',
    'admin.diskon.*' => 'menu.diskon',
    'admin.pembayaran-bulanan.*' => 'menu.rekap-pembayaran',
    'admin.kritik-saran.*' => 'menu.kritik-saran',
    'admin.orangtua-chat.*' => 'menu.chat-orangtua',
    'admin.role.*' => 'menu.role',
    'admin.pengguna.*' => 'menu.pengguna',
    'admin.akuntansi-setting.*' => 'menu.setting-akuntansi',
    'admin.ai-persona.*' => 'menu.pengaturan-ai',
    'admin.ai.feedback-suggestions' => 'menu.pengaturan-ai',
  ],
];
