<?php

namespace App\Support;

use App\Models\CmsContent;

final class GuestCms
{
    /**
     * @return array<string, string>
     */
    public static function data(): array
    {
        $brand = GuestBrand::name();

        return [
            'hero_title' => CmsContent::get('hero_title', 'Kelola Operasional PAUD & Pantau Tumbuh Kembang Anak Lebih Praktis'),
            'hero_subtitle' => CmsContent::get('hero_subtitle', 'Satu platform untuk admin, guru, dan orang tua—presensi, komunikasi, laporan harian, dan dokumentasi tumbuh kembang tanpa pekerjaan berulang.'),
            'hero_photo' => CmsContent::get('hero_photo', ''),
            'hero_photo_alt' => CmsContent::get('hero_photo_alt', ''),
            'hero_left_photo' => CmsContent::get('hero_left_photo', ''),
            'hero_right_photo' => CmsContent::get('hero_right_photo', ''),
            'about_title' => CmsContent::get('about_title', 'Mengapa DaycareAI?'),
            'about_text' => CmsContent::get('about_text', "DaycareAI hadir untuk tiga hal penting: menjembatani komunikasi orang tua dan sekolah secara transparan, menyederhanakan operasional harian tim admin dan guru, serta mempermudah dokumentasi dan pelaporan yang repetitif.\n\nBukan sekadar software dengan banyak menu — DaycareAI dirancang agar setiap pihak merasakan manfaat nyata setiap hari."),
            'about_photo' => CmsContent::get('about_photo', ''),
            'about_photo_alt' => CmsContent::get('about_photo_alt', ''),
            'facility_1_title' => CmsContent::get('facility_1_title', 'Penghubung Ortu & Sekolah'),
            'facility_1_desc' => CmsContent::get('facility_1_desc', 'Portal orang tua, presensi, pencapaian, monev, pembayaran, dan komunikasi dua arah.'),
            'facility_1_icon' => CmsContent::get('facility_1_icon', 'service-ortu.svg'),
            'facility_2_title' => CmsContent::get('facility_2_title', 'Operasional Internal'),
            'facility_2_desc' => CmsContent::get('facility_2_desc', 'Siswa, kelas, kegiatan, presensi guru, menu makanan, dan keuangan PSAK.'),
            'facility_2_icon' => CmsContent::get('facility_2_icon', 'service-operasional.svg'),
            'facility_3_title' => CmsContent::get('facility_3_title', 'Laporan & Dokumentasi'),
            'facility_3_desc' => CmsContent::get('facility_3_desc', 'Monev, pencapaian, dan ringkasan kegiatan yang rapi untuk orang tua dan arsip sekolah.'),
            'facility_3_icon' => CmsContent::get('facility_3_icon', 'service-ai.svg'),
            'facility_4_title' => CmsContent::get('facility_4_title', 'Komunikasi Sekolah'),
            'facility_4_desc' => CmsContent::get('facility_4_desc', 'Chat orang tua, kritik saran, dan pengumuman dalam satu saluran terpusat.'),
            'facility_4_icon' => CmsContent::get('facility_4_icon', 'service-komunikasi.svg'),
            'gallery_1' => CmsContent::get('gallery_1', ''),
            'gallery_2' => CmsContent::get('gallery_2', ''),
            'gallery_3' => CmsContent::get('gallery_3', ''),
            'gallery_4' => CmsContent::get('gallery_4', ''),
            'gallery_5' => CmsContent::get('gallery_5', ''),
            'gallery_6' => CmsContent::get('gallery_6', ''),
            'gallery_1_alt' => CmsContent::get('gallery_1_alt', ''),
            'gallery_2_alt' => CmsContent::get('gallery_2_alt', ''),
            'gallery_3_alt' => CmsContent::get('gallery_3_alt', ''),
            'gallery_4_alt' => CmsContent::get('gallery_4_alt', ''),
            'gallery_5_alt' => CmsContent::get('gallery_5_alt', ''),
            'gallery_6_alt' => CmsContent::get('gallery_6_alt', ''),
            'kontak_alamat' => CmsContent::get('kontak_alamat', 'Jl. Taman Lembayung No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah (50273)'),
            'kontak_telepon' => CmsContent::get('kontak_telepon', GuestWhatsApp::DISPLAY),
            'kontak_email' => CmsContent::get('kontak_email', 'admin@firstudio.id'),
            'kontak_jam' => CmsContent::get('kontak_jam', 'Senin–Jumat: 08.00–17.00 WIB'),
            'footer_text' => CmsContent::get('footer_text', 'Menghubungkan orang tua dan sekolah, mempermudah operasional, dan mendukung pertumbuhan PAUD Indonesia.'),
            'seo_meta_title' => CmsContent::get('seo_meta_title', ''),
            'seo_meta_description' => CmsContent::get('seo_meta_description', ''),
            'seo_og_image' => CmsContent::get('seo_og_image', ''),
            'seo_focus_keyword' => CmsContent::get('seo_focus_keyword', ''),
            'section_stats_title' => CmsContent::get('section_stats_title', 'Nilai yang Anda dapatkan'),
            'section_stats_subtitle' => CmsContent::get('section_stats_subtitle', 'DaycareAI dirancang untuk transparansi ortu–sekolah, operasional yang lebih ringan, dan data yang terkelola dengan baik.'),
            'section_features_title' => CmsContent::get('section_features_title', 'Fitur utama DaycareAI'),
            'section_features_subtitle' => CmsContent::get('section_features_subtitle', 'Empat pilar yang mendukung operasional PAUD Anda setiap hari.'),
            'section_gallery_title' => CmsContent::get('section_gallery_title', 'Galeri kegiatan'),
            'section_gallery_subtitle' => CmsContent::get('section_gallery_subtitle', 'Cuplikan aktivitas dan lingkungan belajar yang dikelola lewat DaycareAI.'),
            'section_testimonial_title' => CmsContent::get('section_testimonial_title', 'Apa kata pengguna'),
            'section_testimonial_subtitle' => CmsContent::get('section_testimonial_subtitle', 'Cerita dari admin sekolah, lembaga, dan orang tua yang memakai DaycareAI.'),
            'section_cta_title' => CmsContent::get('section_cta_title', 'Mulai digitalisasi PAUD Anda'),
            'section_cta_subtitle' => CmsContent::get('section_cta_subtitle', 'Daftarkan sekolah atau hubungi tim kami untuk demo dan konsultasi.'),
            'stats_1_value' => CmsContent::get('stats_1_value', 'Real-time'),
            'stats_1_label' => CmsContent::get('stats_1_label', 'Transparansi ortu–sekolah'),
            'stats_2_value' => CmsContent::get('stats_2_value', 'Terpadu'),
            'stats_2_label' => CmsContent::get('stats_2_label', 'Satu platform operasional'),
            'stats_3_value' => CmsContent::get('stats_3_value', 'Mudah'),
            'stats_3_label' => CmsContent::get('stats_3_label', 'Memudahkan admin & guru'),
            'stats_4_value' => CmsContent::get('stats_4_value', 'Aman'),
            'stats_4_label' => CmsContent::get('stats_4_label', 'Data sekolah terkelola'),
            'faq_title' => CmsContent::get('faq_title', 'Pertanyaan yang sering diajukan'),
            'faq_1_q' => CmsContent::get('faq_1_q', "Apa itu {$brand}?"),
            'faq_1_a' => CmsContent::get('faq_1_a', 'Platform terpadu untuk operasional PAUD: data siswa, presensi, komunikasi orang tua, keuangan, dan dokumentasi kegiatan dalam satu sistem.'),
            'faq_2_q' => CmsContent::get('faq_2_q', 'Bagaimana cara mendaftarkan sekolah?'),
            'faq_2_a' => CmsContent::get('faq_2_a', 'Klik Daftar Sekolah di halaman ini, isi formulir, lalu tim kami akan menghubungi Anda untuk onboarding dan demo.'),
            'faq_3_q' => CmsContent::get('faq_3_q', 'Apakah orang tua punya akses aplikasi?'),
            'faq_3_a' => CmsContent::get('faq_3_a', 'Ya. Orang tua dapat memantau kehadiran, pencapaian, pembayaran, dan berkomunikasi dengan sekolah melalui portal khusus.'),
            'faq_image' => CmsContent::get('faq_image', ''),
            'blog_1_image' => CmsContent::get('blog_1_image', ''),
            'blog_2_image' => CmsContent::get('blog_2_image', ''),
            'blog_3_image' => CmsContent::get('blog_3_image', ''),
            'about_collage_image' => CmsContent::get('about_collage_image', ''),
            'newsletter_image' => CmsContent::get('newsletter_image', ''),
            'section_student_age_title' => CmsContent::get('section_student_age_title', "{$brand} mendukung pengelolaan PAUD dan jenjang usia dini"),
            'section_student_age_text' => CmsContent::get('section_student_age_text', 'Kelola kelompok usia, rombel, dan perkembangan anak dengan data yang rapi dan mudah diakses guru serta orang tua.'),
            'section_blog_title' => CmsContent::get('section_blog_title', 'Wawasan seputar PAUD dan digitalisasi sekolah'),
            'testimonial_1_title' => CmsContent::get('testimonial_1_title', 'Orang tua lebih tenang'),
            'testimonial_1_quote' => CmsContent::get('testimonial_1_quote', 'Saya bisa cek kehadiran dan pencapaian anak kapan saja. Tidak perlu menunggu rapat bulanan untuk tahu perkembangannya.'),
            'testimonial_1_name' => CmsContent::get('testimonial_1_name', 'Ibu Sari'),
            'testimonial_1_role' => CmsContent::get('testimonial_1_role', 'Orang Tua PAUD'),
            'testimonial_2_title' => CmsContent::get('testimonial_2_title', 'Admin jadi lebih efisien'),
            'testimonial_2_quote' => CmsContent::get('testimonial_2_quote', 'Pendaftaran, presensi, dan pembayaran dalam satu sistem. Tim kami hemat berjam-jam kerja administratif setiap minggu.'),
            'testimonial_2_name' => CmsContent::get('testimonial_2_name', 'Budi Santoso'),
            'testimonial_2_role' => CmsContent::get('testimonial_2_role', 'Admin Sekolah'),
            'testimonial_3_title' => CmsContent::get('testimonial_3_title', 'Mudah kelola multi-cabang'),
            'testimonial_3_quote' => CmsContent::get('testimonial_3_quote', "Sebagai lembaga dengan tiga cabang, {$brand} membantu kami memantau operasional dan komunikasi orang tua secara terpusat."),
            'testimonial_3_name' => CmsContent::get('testimonial_3_name', 'Dewi Lestari'),
            'testimonial_3_role' => CmsContent::get('testimonial_3_role', 'Ketua Lembaga'),
            'page_tentang_h1' => CmsContent::get('page_tentang_h1', 'Tentang Kami'),
            'seo_tentang_description' => CmsContent::get('seo_tentang_description', "Kenali {$brand} — platform PAUD yang menghubungkan orang tua dan sekolah, mempermudah operasional, didukung AI."),
            'page_fasilitas_h1' => CmsContent::get('page_fasilitas_h1', 'Fitur'),
            'seo_fasilitas_description' => CmsContent::get('seo_fasilitas_description', "Fitur lengkap {$brand} — portal orang tua, operasional sekolah, keuangan PSAK, presensi, dan asisten AI."),
            'page_galeri_h1' => CmsContent::get('page_galeri_h1', 'Galeri'),
            'page_galeri_intro' => CmsContent::get('page_galeri_intro', 'Cuplikan dashboard dan modul yang digunakan sehari-hari oleh lembaga, admin, pengajar, dan orang tua.'),
            'seo_galeri_description' => CmsContent::get('seo_galeri_description', "Galeri tampilan {$brand} — screenshot modul dan aktivitas platform PAUD."),
            'page_kontak_h1' => CmsContent::get('page_kontak_h1', 'Hubungi Kami'),
            'seo_kontak_description' => CmsContent::get('seo_kontak_description', "Hubungi tim {$brand} untuk demo, penawaran, dan konsultasi implementasi platform PAUD Anda."),
            'contact_form_h2' => CmsContent::get('contact_form_h2', 'Minta demo & penawaran'),
            'contact_form_lead' => CmsContent::get('contact_form_lead', ''),
            'pillar_1_title' => CmsContent::get('pillar_1_title', ''),
            'pillar_1_desc' => CmsContent::get('pillar_1_desc', ''),
            'pillar_2_title' => CmsContent::get('pillar_2_title', ''),
            'pillar_2_desc' => CmsContent::get('pillar_2_desc', ''),
            'pillar_3_title' => CmsContent::get('pillar_3_title', ''),
            'pillar_3_desc' => CmsContent::get('pillar_3_desc', ''),
            'page_pendaftaran_h2' => CmsContent::get('page_pendaftaran_h2', 'Orang tua & anak'),
            'page_pendaftaran_intro' => CmsContent::get('page_pendaftaran_intro', "Daftarkan akun untuk sekolah mitra {$brand}."),
            'page_daftar_sekolah_h1' => CmsContent::get('page_daftar_sekolah_h1', 'Pendaftaran Akun Sekolah'),
            'page_daftar_sekolah_intro' => CmsContent::get('page_daftar_sekolah_intro', 'Mulai digitalisasi PAUD — tim kami akan meninjau pendaftaran sebelum akun admin diaktifkan.'),
            'page_daftar_lembaga_h1' => CmsContent::get('page_daftar_lembaga_h1', 'Daftarkan Lembaga Anda'),
            'page_daftar_lembaga_intro' => CmsContent::get('page_daftar_lembaga_intro', 'Isi formulir di bawah. Tim kami akan meninjau pendaftaran sebelum akun diaktifkan.'),
        ];
    }
}
